set(CMAKE_CXX_COMPILER arm-none-eabi-g++)
set(CMAKE_C_COMPILER arm-none-eabi-gcc)

set(CMAKE_EXECUTABLE_SUFFIX_CXX .elf)
set(CMAKE_EXECUTABLE_SUFFIX_C .elf)
set(CMAKE_EXECUTABLE_SUFFIX_ASM .elf)

list(APPEND CMAKE_ASM_SOURCE_FILE_EXTENSIONS "arm")

set(CMAKE_EXE_LINKER_FLAGS "--specs=rdimon.specs -nostartfiles")

set(CMAKE_C_FLAGS_INIT "-march=armv7-a -marm -DCPU_A9")
set(CMAKE_CXX_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(CMAKE_ASM_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${CMAKE_C_FLAGS_INIT}")
