name: build_and_test

on: [push]

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: build
              uses: MitchellThompkins/cocoOS_github_action@v0.0.4.dev
              with:
                command: make build.all

            - name: test
              uses: MitchellThompkins/cocoOS_github_action@v0.0.4.dev
              with:
                command: make test check-trace
