name: build_and_test

on:
  push:
  pull_request:

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        conatiner:
            image: ghcr.io/mitchellthompkins/embedded_sdk:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Build tests
              #TODO(@mthompkins): fix these scripts
              run: |
                    make build.a9
                    make qemu-run.a9
