name: build_and_test

on: [push]

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: cocoOS-CI
              uses: MitchellThompkins/cocoOS_github_action@v0.0.3
              with:
                command: echo "hello world"
                #command: qemu-system-arm --version
                #command: make build.a9

              #- name: Run Tests
              #  uses: actions/cocoOS-CI@v0.0.1
              #  with:
              #      command: make qemu-run.a9
